baseurl = "/"
languageCode = "en-US"
title = "Kyle Gu"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/post/:year/:month/:day/:slug"

[params]
  avatar = "profile.JPG"
  author = "Kyle Gu"
  occupation = "pre-medical biology major"
  about = "I love hip hop, sports, traveling, Netflix, and boba."

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "kylejgu"
  Email         = "kylegu88@yahoo.com"
  Twitter       = "DrKyleGu"
#  LinkedIn      = "username"
  Instagram     = "kylejgu"
#  Stackoverflow = "username"
#  Medium        = "username"
#  Telegram      = "username"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/post/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"
